using System;
using UnityEngine;

namespace ChainsOfFate.Gerallt
{
    public abstract class WeaponBase : MonoBehaviour, IDescriptive
    {
        #region Fields
        
        /// <summary>
        /// The ID of the weapon. Internally generated by a GUID.
        /// No need to manually set this.
        /// </summary>
        private string id;

        [SerializeField] private string weaponName;
        [SerializeField] private string weaponDescription;
        [SerializeField] private int baseDamage;
        [SerializeField] private float statusPercentage;
        [SerializeField] private Color representation;
        [SerializeField] private bool randomTintColour = true;
        
        #endregion

        #region Properties

        public string ID => id;

        public string WeaponName
        {
            get => weaponName;
            set
            {
                weaponName = value;
                RaiseStatChanged("WeaponName", value);
            }
        }
        
        public int BaseDamage
        {
            get => baseDamage;
            set
            {
                baseDamage = value;
                RaiseStatChanged("BaseDamage", value);
            }
        }
        
        public float StatusPercentage
        {
            get => statusPercentage;
            set
            {
                statusPercentage = value;
                RaiseStatChanged("StatusPercentage", value);
            }
        }
        
        public string WeaponDescription
        {
            get => weaponDescription;
            set
            {
                weaponDescription = value;
                RaiseStatChanged("WeaponDescription", value);
            }
        }

        #endregion

        // Unity can't serialise properties which is a shame. Because when properties change we could call RaiseStatChanged() internally.
        public delegate void StatChangeDelegate(WeaponBase weapon, string propertyName, object newValue);

        public event StatChangeDelegate OnStatChanged;

        public virtual void UpdatePrimaryStats()
        {
            RaiseStatChanged("ID", ID);
            RaiseStatChanged("WeaponName", WeaponName);
            RaiseStatChanged("BaseDamage", BaseDamage);
            RaiseStatChanged("StatusPercentage", StatusPercentage);
            RaiseStatChanged("WeaponDescription", WeaponDescription);
        }

        protected void RaiseStatChanged(string propertyName, object newValue)
        {
            OnStatChanged?.Invoke(this, propertyName, newValue);
        }

        public string GetId()
        {
            return ID;
        }
        
        public string GetName()
        {
            return WeaponName;
        }

        public string GetDescription()
        {
            return WeaponDescription;
        }
        
        public Color GetTint()
        {
            return representation;
        }

        public virtual void Awake()
        {
            Guid newId = Guid.NewGuid(); //TODO: Check for collisions with weapons that by pure unluck might have the same GUID.
            id = newId.ToString();
            
            if (randomTintColour)
            {
                representation = GameManager.RandomColour();
            }
        }
    }
}